### PR TITLE
ConnectionPool: monitor idle connections

### LINKED ISSUE #199: More info for debugging `EOFError`s
I keep hitting random `EOFError`s while running an `HTTP.post` request against a server. Is there a way to get HTTP.jl to print out whatever it found prior to getting the `EOFError`?

### LINKED ISSUE #214: Analysis of EOF Errors with GitHub API (Seems Resolved)
Using `verbose=3` and `DEBUG_LEVEL=3`.
Using the `retry_post_requests` branch (no keepalive) _-- note: this branch (and the MbedTLS bug fix the goes with it) is now merged into master_

Note that my POST request to GitHub fails with a 404, but this does not effect the test.
The test is trying to observer the behaviour what a POST request is sent on a connection that has been sitting idle for a while. The 404 result is not important.

First request to create a gist, get a response without issue.
```julia
julia> using GitHub ; token = "XXX" ; myauth = GitHub.authenticate(token)

DEBUG: 581e SSL connect: api.github.com:443...
DEBUG: 581e TCP connect: api.github.com:443...
DEBUG: 581e 🔗  New:            ⏸    0↑     0↓    api.github.com:443:63915 ≣16 RawFD(23)
DEBUG: 581e 👁  Start write:T0  ⏸    0↑     0↓    api.github.com:443:63915 ≣16 RawFD(23)
DEBUG: 581e 👁  Start read: T0  ⏸    0↑🔒    0↓    api.github.com:443:63915 ≣16 RawFD(23)
DEBUG: e0ca 🗣  Write done: T0  ⏸    1↑     0↓    api.github.com:443:63915 ≣16 RawFD(23)
DEBUG: 581e ✉️  Read done:  T0  ⏸    1↑     1↓    api.github.com:443:63915 ≣16 RawFD(23)
GitHub.OAuth2(1e2b86**********************************)

julia> GitHub.create_gist(auth=myauth; params= Dict(["description" => "foo", "public" => false, "files" => Dict([ "f1" => "foo" ])]))
DEBUG: 581e ♻️  Idle:           ⏸    1↑     1↓    api.github.com:443:63915 ≣16 RawFD(23)
DEBUG: 581e 👁  Start write:T1  ⏸    1↑     1↓    api.github.com:443:63915 ≣16 RawFD(23)
➡️   "POST /gists HTTP/1.1\r\n"
➡️   "Authorization: token 1e2b86bXX32e7415f590c196b7\r\n"
➡️   "User-Agent: GitHub-jl\r\n"
➡️   "Host: api.github.com\r\n"
➡️   "Content-Length: 57\r\n"
➡️   "\r\n"
DEBUG: 581e 👁  Start read: T1  ⏸    1↑🔒    1↓    api.github.com:443:63915 ≣16 RawFD(23)
➡️   "{\"public\":false,\"files\":{\"f1\":\"foo\"},\"description\":\"foo\"}"
DEBUG: b31b 🔒  POST non-idempotent, holding write lock: T1  🔁    1↑🔒    1↓🔒   api.github.com:443:63915 ≣16 RawFD(23)
⬅️   "HTTP/1.1 404 Not Found\r\n"
    "Date: Sat, 03 Mar 2018 10:08:16 GMT\r\n"
 -- snip --

julia> HTTP.ConnectionPool.showpool(STDOUT)
ConnectionPool[
   ⏸    2↑     2↓    api.github.com:443:63915 ≣16 RawFD(23)
]
```
^ connection pool shows a single connection that has been used twice (once to get the auth token and once for the POST).

After waiting 10 seconds, the request works as before...
```julia
julia> sleep(10)

julia> HTTP.ConnectionPool.showpool(STDOUT)
ConnectionPool[
   ⏸    2↑     2↓    api.github.com:443:63915 ≣16 RawFD(23)
]

julia> GitHub.create_gist(auth=myauth; params= Dict(["description" => "foo", "public" => false, "files" => Dict([ "f1" => "foo" ])]))
DEBUG: 581e ♻️  Idle:           ⏸    2↑     2↓    api.github.com:443:63915 ≣16 RawFD(23)
DEBUG: 581e 👁  Start write:T2  ⏸    2↑     2↓    api.github.com:443:63915 ≣16 RawFD(23)
➡️   "POST /gists HTTP/1.1\r\n"
➡️   "Authorization: token 1e2b86bXX2e7415f590c196b7\r\n"
➡️   "User-Agent: GitHub-jl\r\n"
➡️   "Host: api.github.com\r\n"
➡️   "Content-Length: 57\r\n"
➡️   "\r\n"
DEBUG: 581e 👁  Start read: T2  ⏸    2↑🔒    2↓    api.github.com:443:63915 ≣16 RawFD(23)
➡️   "{\"public\":false,\"files\":{\"f1\":\"foo\"},\"description\":\"foo\"}"
DEBUG: 06d5 🔒  POST non-idempotent, holding write lock: T2  🔁    2↑🔒    2↓🔒   api.github.com:443:63915 ≣16 RawFD(23)
⬅️   "HTTP/1.1 404 Not Found\r\n"
    "Date: Sat, 03 Mar 2018 10:08:49 GMT\r\n"
    "Content-Type: application/json; charset=utf-8\r\n"
    -- snip --
```

After waiting 30 seconds, the request still works...

```julia
julia> sleep(30)

julia> HTTP.ConnectionPool.showpool(STDOUT)
ConnectionPool[
   ⏸    3↑     3↓    api.github.com:443:63915 ≣16 RawFD(23)
]


julia> GitHub.create_gist(auth=myauth; params= Dict(["description" => "foo", "public" => false, "files" => Dict([ "f1" => "foo" ])]))
DEBUG: 581e ♻️  Idle:           ⏸    3↑     3↓    api.github.com:443:63915 ≣16 RawFD(23)
DEBUG: 581e 👁  Start write:T3  ⏸    3↑     3↓    api.github.com:443:63915 ≣16 RawFD(23)
➡️   "POST /gists HTTP/1.1\r\n"
➡️   "Authorization: token 1e2b86bd089b8XX7415f590c196b7\r\n"
➡️   "User-Agent: GitHub-jl\r\n"
➡️   "Host: api.github.com\r\n"
➡️   "Content-Length: 57\r\n"
➡️   "\r\n"
DEBUG: 581e 👁  Start read: T3  ⏸    3↑🔒    3↓    api.github.com:443:63915 ≣16 RawFD(23)
➡️   "{\"public\":false,\"files\":{\"f1\":\"foo\"},\"description\":\"foo\"}"
DEBUG: 61da 🔒  POST non-idempotent, holding write lock: T3  🔁    3↑🔒    3↓🔒   api.github.com:443:63915 ≣16 RawFD(23)
⬅️   "HTTP/1.1 404 Not Found\r\n"
    "Date: Sat, 03 Mar 2018 10:09:31 GMT\r\n"
    "Content-Type: application/json; charset=utf-8\r\n"
 -- snip --

julia> HTTP.ConnectionPool.showpool(STDOUT)
ConnectionPool[
   ⏸    4↑     4↓    api.github.com:443:63915 ≣16 RawFD(23)
]
```

After waiting 60 seconds, the connection pool now show the connection in ["connected" state rather than "paused" state](https://github.com/JuliaLang/julia/blob/ce26ed0c132720bd30b4c1551c009c4a507a9276/base/stream.jl#L85) but I don't think this really tells us anything other than that some local timeout has expired.

```julia
julia> sleep(60)

julia> HTTP.ConnectionPool.showpool(STDOUT)
ConnectionPool[
   🔗    4↑     4↓    api.github.com:443:63915 ≣16 RawFD(23)
]
```

When the request is sent this time, it fails with an EOFError.
But, with the changes on the `retry_post_requests` branch, the request is now retried.
This means that even with the very tiny POST body used in the test, the connection failure is now detected before the body is sent. I assume that the failure is happening as soon as we try to read the response headers (which now happens before the body is sent).

```julia
julia> GitHub.create_gist(auth=myauth; params= Dict(["description" => "foo", "public" => false, "files" => Dict([ "f1" => "foo" ])]))
DEBUG: 581e ♻️  Idle:           🔗    4↑     4↓    api.github.com:443:63915 ≣16 RawFD(23)
DEBUG: 581e 👁  Start write:T4  🔗    4↑     4↓    api.github.com:443:63915 ≣16 RawFD(23)
➡️   "POST /gists HTTP/1.1\r\n"
➡️   "Authorization: token 1e2b86bd089b885fXX7415f590c196b7\r\n"
➡️   "User-Agent: GitHub-jl\r\n"
➡️   "Host: api.github.com\r\n"
➡️   "Content-Length: 57\r\n"
➡️   "\r\n"
DEBUG: 581e 👁  Start read: T4  🔗    4↑🔒    4↓    api.github.com:443:63915 ≣16 RawFD(23)
➡️   "{\"public\":false,\"files\":{\"f1\":\"foo\"},\"description\":\"foo\"}"
DEBUG: 581e ❗️  ConnectionLayer EOFError(). Closing: T4  💀    4↑🔒    4↓🔒   api.github.com:443:63915 ≣16 RawFD(-1)
DEBUG: 581e 🗣  Write done: T4  💀    5↑     4↓🔒   api.github.com:443:63915 ≣16 RawFD(-1)
DEBUG: 581e ✉️  Read done:  T4  💀    5↑     5↓    api.github.com:443:63915 ≣16 RawFD(-1)
DEBUG: 581e 🔄  Retry IOError(EOFError() during request(https://@api.github.com:/gists?#))
: POST /gists HTTP/1.1
DEBUG: 581e 🗑  Deleted:        💀    5↑     5↓    api.github.com:443:63915 ≣16 RawFD(-1)
DEBUG: 581e SSL connect: api.github.com:443...
DEBUG: 581e TCP connect: api.github.com:443...
DEBUG: 581e 🔗  New:            ⏸    0↑     0↓    api.github.com:443:63931 ≣16 RawFD(23)
DEBUG: 581e 👁  Start write:T0  ⏸    0↑     0↓    api.github.com:443:63931 ≣16 RawFD(23)
➡️   "POST /gists HTTP/1.1\r\n"
➡️   "Authorization: token 1e2b86bd089XX2e7415f590c196b7\r\n"
➡️   "User-Agent: GitHub-jl\r\n"
➡️   "Host: api.github.com\r\n"
➡️   "Content-Length: 57\r\n"
➡️   "\r\n"
DEBUG: 581e 👁  Start read: T0  ⏸    0↑🔒    0↓    api.github.com:443:63931 ≣16 RawFD(23)
➡️   "{\"public\":false,\"files\":{\"f1\":\"foo\"},\"description\":\"foo\"}"
DEBUG: 02b4 🔒  POST non-idempotent, holding write lock: T0  🔁    0↑🔒    0↓🔒   api.github.com:443:63931 ≣16 RawFD(23)
⬅️   "HTTP/1.1 404 Not Found\r\n"
    "Date: Sat, 03 Mar 2018 10:10:53 GMT\r\n"
    "Content-Type: application/json; charset=utf-8\r\n"
  -- snip--
```

Now there is a new connection in the pool:
```julia
julia> HTTP.ConnectionPool.showpool(STDOUT)
ConnectionPool[
   ⏸    1↑     1↓    api.github.com:443:63931 ≣16 RawFD(23)
]
```

### LINKED ISSUE #220: EOFError when parsing headers (dupe of #214)
Seen on Nanosoldier:
```
ERROR (unhandled task failure): IOError(EOFError() during request(https://api.github.com/repos/JuliaLang/julia/statuses/5621642cc480266f018ad1c1892ec9e8d2d3cf7f))
Stacktrace:
 [1] readuntil(::HTTP.ConnectionPool.Transaction{MbedTLS.SSLContext}, ::HTTP.Parsers.#find_end_of_header) at /home/nanosoldier/.julia/v0.6/HTTP/src/IOExtras.jl:169
 [2] readheaders(::HTTP.ConnectionPool.Transaction{MbedTLS.SSLContext}, ::HTTP.Messages.Response) at /home/nanosoldier/.julia/v0.6/HTTP/src/Messages.jl:464
 [3] startread(::HTTP.Streams.Stream{HTTP.Messages.Response,HTTP.ConnectionPool.Transaction{MbedTLS.SSLContext}}) at /home/nanosoldier/.julia/v0.6/HTTP/src/Streams.jl:145
 [4] macro expansion at /home/nanosoldier/.julia/v0.6/HTTP/src/StreamRequest.jl:51 [inlined]
 [5] macro expansion at ./task.jl:302 [inlined]
 [6] #request#1(::Void, ::Void, ::Int64, ::Array{Any,1}, ::Function, ::Type{HTTP.StreamRequest.StreamLayer}, ::HTTP.ConnectionPool.Transaction{MbedTLS.SSLContext}, ::HTTP.Messages.Request, ::String) at /home/nanosoldier/.julia/v0.6/HTTP/src/StreamRequest.jl:47
 [7] (::HTTP.#kw##request)(::Array{Any,1}, ::HTTP.#request, ::Type{HTTP.StreamRequest.StreamLayer}, ::HTTP.ConnectionPool.Transaction{MbedTLS.SSLContext}, ::HTTP.Messages.Request, ::String) at ./<missing>:0
 [8] #request#1(::Type{T} where T, ::Array{Any,1}, ::Function, ::Type{HTTP.ConnectionRequest.ConnectionPoolLayer{HTTP.StreamRequest.StreamLayer}}, ::HTTP.URIs.URI, ::HTTP.Messages.Request, ::String) at /home/nanosoldier/.julia/v0.6/HTTP/src/ConnectionRequest.jl:32
 [9] (::HTTP.#kw##request)(::Array{Any,1}, ::HTTP.#request, ::Type{HTTP.ConnectionRequest.ConnectionPoolLayer{HTTP.StreamRequest.StreamLayer}}, ::HTTP.URIs.URI, ::HTTP.Messages.Request, ::String) at ./<missing>:0
 [10] (::Base.###49#50#52{ExponentialBackOff,HTTP.RetryRequest.##2#3{Bool,HTTP.Messages.Request},HTTP.#request})(::Array{Any,1}, ::Function, ::Type{T} where T, ::Vararg{Any,N} where N) at ./error.jl:139
 [11] (::Base.#kw###49#51)(::Array{Any,1}, ::Base.##49#51, ::Type{T} where T, ::Vararg{Any,N} where N) at ./<missing>:0
 [12] #request#1(::Int64, ::Bool, ::Array{Any,1}, ::Function, ::Type{HTTP.RetryRequest.RetryLayer{HTTP.ConnectionRequest.ConnectionPoolLayer{HTTP.StreamRequest.StreamLayer}}}, ::HTTP.URIs.URI, ::HTTP.Messages.Request, ::String) at /home/nanosoldier/.julia/v0.6/HTTP/src/RetryRequest.jl:43
 [13] (::HTTP.#kw##request)(::Array{Any,1}, ::HTTP.#request, ::Type{HTTP.RetryRequest.RetryLayer{HTTP.ConnectionRequest.ConnectionPoolLayer{HTTP.StreamRequest.StreamLayer}}}, ::HTTP.URIs.URI, ::HTTP.Messages.Request, ::String) at ./<missing>:0
 [14] #request#1(::VersionNumber, ::String, ::Void, ::Void, ::Array{Any,1}, ::Function, ::Type{HTTP.MessageRequest.MessageLayer{HTTP.RetryRequest.RetryLayer{HTTP.ConnectionRequest.ConnectionPoolLayer{HTTP.StreamRequest.StreamLayer}}}}, ::String, ::HTTP.URIs.URI, ::Array{Pair{SubString{String},SubString{String}},1}, ::String) at /home/nanosoldier/.julia/v0.6/HTTP/src/MessageRequest.jl:44
 [15] (::HTTP.#kw##request)(::Array{Any,1}, ::HTTP.#request, ::Type{HTTP.MessageRequest.MessageLayer{HTTP.RetryRequest.RetryLayer{HTTP.ConnectionRequest.ConnectionPoolLayer{HTTP.StreamRequest.StreamLayer}}}}, ::String, ::HTTP.URIs.URI, ::Array{Pair{SubString{String},SubString{String}},1}, ::String) at ./<missing>:0
 [16] #request#1(::Int64, ::Bool, ::Array{Any,1}, ::Function, ::Type{HTTP.RedirectRequest.RedirectLayer{HTTP.MessageRequest.MessageLayer{HTTP.RetryRequest.RetryLayer{HTTP.ConnectionRequest.ConnectionPoolLayer{HTTP.StreamRequest.StreamLayer}}}}}, ::String, ::HTTP.URIs.URI, ::Array{Pair{SubString{String},SubString{String}},1}, ::String) at /home/nanosoldier/.julia/v0.6/HTTP/src/RedirectRequest.jl:24
 [17] (::HTTP.#kw##request)(::Array{Any,1}, ::HTTP.#request, ::Type{HTTP.RedirectRequest.RedirectLayer{HTTP.MessageRequest.MessageLayer{HTTP.RetryRequest.RetryLayer{HTTP.ConnectionRequest.ConnectionPoolLayer{HTTP.StreamRequest.StreamLayer}}}}}, ::String, ::HTTP.URIs.URI, ::Array{Pair{SubString{String},SubString{String}},1}, ::String) at ./<missing>:0
 [18] #request#8(::Array{Any,1}, ::Function, ::String, ::HTTP.URIs.URI, ::Array{Pair{SubString{String},SubString{String}},1}, ::String) at /home/nanosoldier/.julia/v0.6/HTTP/src/HTTP.jl:289
 [19] (::HTTP.#kw##request)(::Array{Any,1}, ::HTTP.#request, ::String, ::HTTP.URIs.URI, ::Array{Pair{SubString{String},SubString{String}},1}, ::String) at ./<missing>:0
 [20] #request#9(::Dict{String,String}, ::String, ::Void, ::Array{Any,1}, ::Function, ::String, ::String, ::Dict{String,String}, ::String) at /home/nanosoldier/.julia/v0.6/HTTP/src/HTTP.jl:303
 [21] (::HTTP.#kw##request)(::Array{Any,1}, ::HTTP.#request, ::String, ::String, ::Dict{String,String}, ::String) at ./<missing>:0
 [22] #post#13 at /home/nanosoldier/.julia/v0.6/HTTP/src/HTTP.jl:351 [inlined]
 [23] (::HTTP.#kw##post)(::Array{Any,1}, ::HTTP.#post, ::String, ::Dict{String,String}, ::String) at ./<missing>:0
 [24] #github_request#3(::GitHub.OAuth2, ::Bool, ::Dict{Any,Any}, ::Dict{String,String}, ::Bool, ::Function, ::GitHub.GitHubWebAPI, ::Function, ::String) at /home/nanosoldier/.julia/v0.6/GitHub/src/utils/requests.jl:61
 [25] (::GitHub.#kw##github_request)(::Array{Any,1}, ::GitHub.#github_request, ::GitHub.GitHubWebAPI, ::Function, ::String) at ./<missing>:0
 [26] #gh_post#5 at /home/nanosoldier/.julia/v0.6/GitHub/src/utils/requests.jl:68 [inlined]
 [27] (::GitHub.#kw##gh_post)(::Array{Any,1}, ::GitHub.#gh_post, ::GitHub.GitHubWebAPI, ::String) at ./<missing>:0
 [28] #gh_post_json#10(::Array{Any,1}, ::Function, ::GitHub.GitHubWebAPI, ::String) at /home/nanosoldier/.julia/v0.6/GitHub/src/utils/requests.jl:74
 [29] (::GitHub.#kw##gh_post_json)(::Array{Any,1}, ::GitHub.#gh_post_json, ::GitHub.GitHubWebAPI, ::String) at ./<missing>:0
 [30] #create_status#93(::Array{Any,1}, ::Function, ::GitHub.GitHubWebAPI, ::String, ::String) at /home/nanosoldier/.julia/v0.6/GitHub/src/repositories/statuses.jl:31
 [31] (::GitHub.#kw##create_status)(::Array{Any,1}, ::GitHub.#create_status, ::GitHub.GitHubWebAPI, ::String, ::String) at ./<missing>:0
 [32] #create_status#94 at ./<missing>:0 [inlined]
 [33] (::GitHub.#kw##create_status)(::Array{Any,1}, ::GitHub.#create_status, ::String, ::String) at ./<missing>:0
 [34] reply_status(::Nanosoldier.JobSubmission, ::String, ::String, ::Void) at /home/nanosoldier/.julia/v0.6/Nanosoldier/src/submission.jl:111
 [35] reply_status(::Nanosoldier.JobSubmission, ::String, ::String) at /home/nanosoldier/.julia/v0.6/Nanosoldier/src/submission.jl:107
 [36] #reply_status#7(::Array{Any,1}, ::Function, ::Nanosoldier.BenchmarkJob, ::String, ::Vararg{String,N} where N) at /home/nanosoldier/.julia/v0.6/Nanosoldier/src/jobs/jobs.jl:11
 [37] delegate_job(::Nanosoldier.Server, ::Nanosoldier.BenchmarkJob, ::Int64) at /home/nanosoldier/.julia/v0.6/Nanosoldier/src/server.jl:116
 [38] macro expansion at /home/nanosoldier/.julia/v0.6/Nanosoldier/src/server.jl:61 [inlined]
 [39] (::Nanosoldier.##31#32{Nanosoldier.Server})() at ./event.jl:73
```

### PR DESCRIPTION
**Pull request by vtjnash**
When a connection is returned to the (read) pool,
add a monitor to it for receiving unexpected data (or EOF),
and kill / close the Connection object if any activity occurs
before the next write (when it should have simply been waiting idle in the pool)

per https://github.com/JuliaWeb/MbedTLS.jl/pull/145#issuecomment-381832442

closes #214
closes #199
closes #220
closes JuliaWeb/GitHub.jl#106
replaces #235

### CODE REVIEW

**Comment by samoconnor** [comment]
> closes JuliaWeb/GitHub.jl#106

From https://github.com/JuliaWeb/GitHub.jl/issues/106#issuecomment-376711247:
> To be reliable, GitHub.jl will still need to implement state-aware retry of non-idepmontent operations, but the changes above should improve failure rates in the short term

The change in this PR, or #235, and `idle_timeout=` and https://github.com/JuliaWeb/MbedTLS.jl/pull/145, should all help to reduce the probability of the HTTP layer making a non-idepmontent request that cannot be automatically retried. However, the HTTP layer will never handle every corner case. The server can comit a transaction, send "HTTP/1.1 200 OK"  but the network can fail before we get the "OK", it might time out, or we might get a [RST], or a [FIN] depending on the type of failure. Applications that make POST requests will always need to implement application-state-aware retry (or set `retry_non_idempotent=true` if they are sure that is safe).

**Comment by samoconnor** [comment]
I haven't yet reviewed that the busy/count/sequence logic is correct, but I get the point. We want to say "if we are not expecting data".

Compared to #235:
 - I like that this is only active when there is no active transaction.
 - I like that it avoids unexported Base internals.
 - I'm not certian that it plays nicely with TLS. I don't know enought about TLS to know how often OOB alerts will be recieved at random times. Even if close_notify is the only thing we're going to receive, it seems that it would be best to allow the TLS layer to deal with it cleanly. i.e. whatever HTTP.jl does should avoid getting in the way of a clean TLS shutdown.
 - Perhaps we should do the close after a short delay to give the TLS layer to time to clean up nicely. Or, perhaps we should only do this for raw TCP sockets given that MbedTLS.jl should handle this for us via `close_notify`. 

For the purposes of arbitrary local pedantry, I would:
 - Put the monitor in a seperate function so that only one line is added to `closeread`.
 - Keep the postcondition at the end of the function.
 - Re-wrap at 80 cols.
 - Add a `@debug` log message.

**Comment by samoconnor** [comment]
This might be better, i.e. if the connection is EOF (nothing more to read), then close it (signal won't write any more).

```patch
--- a/src/ConnectionPool.jl
+++ b/src/ConnectionPool.jl
@@ -270,7 +270,7 @@ function IOExtras.closeread(t::Transaction)
     # short-circuit if it is already dead or has already started to be reused
     if isopen(t.c) && !t.c.writebusy && (t.c.writecount <= t.sequence + 1) # && !isreadable(t)
         @schedule begin
-            if !eof(t.c.io) && # wait to see if receive any more data
+            if eof(t.c.io) || # wait to see if receive any more data
                     !t.c.readbusy && # and aren't actively expecting to receive data
                     !t.c.writebusy && (t.c.writecount <= t.sequence + 1) # nor have returned from startwrite and/or called closewrite again
                 # other end must be in an invalid state, or terminated the connection:
```

**Comment by samoconnor** [comment]
Hi @vtjnash, @quinnj,
I've pushed a commit to this PR that I think captures the intention of Jameson's proposal:

 - Encapsulate read|writebusy/sequence/count logic in new `isbusy` function.
 - Move `close()` on `eof() || !isbusy()` to new `monitor_idle_connection` function.
 - Make `monitor_idle_connection()` a noop for `::Connection{SSLContext}`

Please review, and please excuse me if I've blatted an important detail in my reinterpretation.

**Comment by vtjnash** [comment]
Lgtm. I was assuming that seeing `eof` implied `close` had already gotten called, but no harm in being explicit. I have no opinion currently on making it a no-op for SSL. We know that it should now be handled there now, but also seems suspect to make these code-paths diverge (mostly just in terms of test coverage though).

File: src/ConnectionPool.jl [hunk 1]
```diff
@@ -264,10 +270,32 @@ function IOExtras.closeread(t::Transaction)
     notify(t.c.readdone)                          ;@debug 2 "✉️  Read done:  $t"
     notify(poolcondition)
 
+    if !isbusy(t.c)
+        @schedule monitor_idle_connection(t.c)
```
Comment (vtjnash) [inline src/ConnectionPool.jl]: maybe worth doing `let c = t.c; @schedule monitor_idle_connection(t.c); end`, so we don't capture all of `t`. But afaik, there's no `finalizers` on `t`, or other way to see this difference.

**Comment by samoconnor** [comment]
>  I was assuming that seeing eof implied close had already gotten called, but no harm in being explicit.

AFAICT `eof() = true` just means we received a [FIN] or a [RST], calling `close()` means we send a [FIN].

File: src/ConnectionPool.jl (hunk 1 above)
Comment (samoconnor) [reply src/ConnectionPool.jl]: Yeah, `t` is an immutable struct containing just `c` and an `Int`, so probably not much difference.
But it's a good reminder to consider what is being captured in closures. I have a feeling I should be more cognisant of that more often...

**Comment by vtjnash** [comment]
Doesn't usually matter, unless you think it's going to be long-lived relative to the object that it wraps and holds lots of other references too.

> calling close() means we send a 

Makes sense. Seems like you're really great at finding bugs, though :)
If we're already in StateEOF, we might (unintentionally) ignore the `close` call: https://github.com/JuliaLang/julia/blob/50413a46a05b4f522e09fac2fb9b6a705cac31d7/base/stream.jl#L322
But we only enter that state for `TTY` objects. Everything else we close immediately upon receipt of an EOF notification: https://github.com/JuliaLang/julia/blob/50413a46a05b4f522e09fac2fb9b6a705cac31d7/base/stream.jl#L480-L488
Should we not do that, and let the user handle this?

**Comment by samoconnor** [comment]
We need to make a fundamental decision:
 - A: Does our IO model distinguish between open-for-read and open-for-write?
  ...and provide an API for [`SHUT_RD` `SHUT_WR` and `SHUT_RDWR`](http://man7.org/linux/man-pages/man2/shutdown.2.html)?, or...
 - B: Does our IO model have only two states?
  open == readable and writeable and
 closed == no reading or writing allowed.

If we go for model A) we can still have convenience methods to hide read vs write (e.g. `close` can do `SHUT_RDWR`) but the spec for the convenience methods will be clearly and generically defined in terms of the read/write aware API.

Going for model B) might not be unreasonable. We could argue that protocols that rely on `SHUT_WR` are archaic and that modern protocols all have higher level mechanisms for connection lifetime control built in these days. This would preclude working with protocols that work like: `TX([Request], [FIN]), RX([Response], [FIN])`. 

In model B), calling `close()` when we get a [FIN] is probably correct. In model A), the fact that the peer has nothing else to send doesn't mean we shouldn't be able to send more to the peer.

The current situation feels like it is somewhere in between, we mostly try to hide the distinction between the send and receive sides of the connection, but then we have `eof()` that queries only the receive state. The current situation is also not consistent across the various `IO` subtypes (https://github.com/JuliaLang/julia/issues/24526)

Either way, I think we need a section under [Interfaces](https://docs.julialang.org/en/latest/manual/interfaces) that lays down the law and a state diagram that shows what sequences of state transitions is allowed and what causes them.

**Comment by vtjnash** [comment]
SHUT_RDWR is a bit different, since it affects the file description, not the file descriptor.

I think model A would be more consistent, especially with things like `AbstractPipe`, where it's meaningful and useful to have a half-duplex pipe. We used to think libuv required a call to `uv_close` in the callback when it reported EOF – which is definitely not true now – which is how Julia ended up here.

Yep, that's the manifestation of that bug.

**Comment by quinnj** [comment]
FWIW, I saw the `KeyError: key TCPSocket(RawFD(-1) closed, 0 bytes waiting) not found` error quite a bit when running this PR under some dev load (w/ MbedTLS master) yesterday. Is there a current workaround? Or we just need to wait for the PR to Base to get merged?

**Comment by vtjnash** [comment]
This PR I think is a no-op for HTTPS workloads

**Comment by samoconnor** [comment]
WIP notes...

| State | Description |
| -- | -- |
| NEW | Valid fd but not connected. Error if reading or writing attempted. | 
| SYN | Connected for writes and reads |
| FIN_WR | Error if writing attempted |
| FIN_RD | Error if reading attempted |
| FIN | fd still valid. Error if reading or writing attempted. No error on status query functions. | 
| CLOSED | fd no longer valid. Error on any operation other than closed query. |

| POSIX | State | Go | Rust | Julia |
| -- | -- | -- | -- | -- |
| | !CLOSED<br>!FIN<br>!FIN_WR | [`SetNoDelay`](https://golang.org/pkg/net/#TCPConn.SetNoDelay) | [`set_nodelay`](https://doc.rust-lang.org/beta/std/net/struct.TcpStream.html#method.set_nodelay) | |
| | !CLOSED<br>!FIN<br>!FIN_WR | [`SetWriteDeadline`](https://golang.org/pkg/net/#IPConn.SetWriteDeadline) | [`set_write_timeout`](https://doc.rust-lang.org/beta/std/net/struct.TcpStream.html#method.set_write_timeout) | |
| [`send`](http://man7.org/linux/man-pages/man2/sendmsg.2.html) | SYN<br>FIN_RD | [`Write`](https://golang.org/pkg/net/#TCPConn.Write)| [`Write`](https://doc.rust-lang.org/beta/std/io/trait.Write.html) | `unsafe_write` |
| [`shutdown(SHUT_WR)`](http://man7.org/linux/man-pages/man2/shutdown.2.html) | SYN -> FIN_WR<br>FIN_RD -> FIN | [`CloseWrite`](https://golang.org/pkg/net/#TCPConn.CloseWrite) | [`shutdown`](https://doc.rust-lang.org/beta/std/net/struct.TcpStream.html#method.shutdown) |[`closewrite`?](https://github.com/JuliaWeb/HTTP.jl/blob/master/src/IOExtras.jl#L4-L5) | 
| | !CLOSED<br>!FIN<br>!FIN_RD | [`SetReadDeadline`](https://golang.org/pkg/net/#IPConn.SetReadDeadline) | [`set_read_timeout`](https://doc.rust-lang.org/beta/std/net/struct.TcpStream.html#method.set_read_timeout) | |
|[`recv`](http://man7.org/linux/man-pages/man2/recvmsg.2.html) | SYN<br>FIN_WR | [`Read`](https://golang.org/pkg/net/#TCPConn.Read) | [`Read`](https://doc.rust-lang.org/beta/std/io/trait.Read.html) | `unsafe_read` |
| [`shutdown(SHUT_RD)`](http://man7.org/linux/man-pages/man2/shutdown.2.html) | SYN -> FIN_RD<br>FIN_WR -> FIN | [`CloseRead`](https://golang.org/pkg/net/#TCPConn.CloseRead)<br> <small>_CloseWrite +<br>CloseRead <br>!= Close_</small> | [`shutdown`](https://doc.rust-lang.org/beta/std/net/struct.TcpStream.html#method.shutdown) | [`closeread`?](https://github.com/JuliaWeb/HTTP.jl/blob/master/src/IOExtras.jl#L4-L5)  | 
| | !CLOSED | [`SetLinger`](https://golang.org/pkg/net/#TCPConn.SetLinger) | | |
| [`close`](http://man7.org/linux/man-pages/man2/close.2.html) | * -> CLOSED | [`Close`](https://golang.org/pkg/net/#TCPConn.Close) | _"when the value is dropped"_ | `close` |

**Comment by samoconnor** [comment]
I would prefer to wait until there is a Julia 0.6.3 with the IdDict bugfix and/or put an `if VERSION...` around  `@schedule monitor_idle_connection` so that this feature is never enabled on a Julia version where it is known to cause the `KeyError` problem.

**Comment by quinnj** [comment]
@vtjnash, what do you think about the status of this PR? can we put versioning so it only applies to 0.7 w/ the idDict bug fixed?

**Comment by samoconnor** [comment]
@quinnj, I've just pushed a commit to this PR to require 0.6.3.
I assume that this should take care of the idDict problem?

**Comment by quinnj** [comment]
@samoconnor, I can reproduce the hang locally on 0.6; it seems to hang on this block: https://github.com/JuliaWeb/HTTP.jl/blob/master/test/loopback.jl#L203. Could you take a look?

**Comment by quinnj** [comment]
Ok, this was actually a conflict of sorts w/ my 0.7 compat PR, which changed `@schedule` blocks to `@async`. Fix is here: https://github.com/JuliaWeb/HTTP.jl/pull/248
